config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :winemakers
  resources :positions
  resources :magazines
  resources :cepas
  resources :wines

  resources :wines do
    resources :cepas 
  end

  post 'wines/:id/winemakers', to: 'wines#add_winemaker', as: 'winemaker_wines'

  

  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_and_belongs_to_many :cepas

  has_many :wine_winemakers
  has_many :winemakers, through: :wine_winemakers
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
    @cepa = Cepa.new

  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
     @winemakers = Winemaker.all
  end

  # POST /wines
  # POST /wines.json
  def create

    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { redirect_back fallback_location: "/" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_winemaker
    @win = Wine.find(params[:id])
    @maker = Winemaker.find(params[:winemaker])
    @win.winemakers << @maker

    redirect_back fallback_location: "/", notice: 'Winemaker agregado correctamente!'
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|


      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { redirect_back fallback_location: "/" }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: "/", notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score)
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.select :score, options_for_select(1..100) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/wines/edit.html.erb
<p style="color:green;"><%= notice %></p>
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= form_with(url: winemaker_wines_path(@wine), local: true) do |form|%>
  <%winemakers_filter = @winemakers.reject{|x| @wine.winemakers.include?(x) }  %>
  <%=form.label :winemakers%>
  <%=form.select :winemaker, options_from_collection_for_select(winemakers_filter, :id, :name)%>
  <%=form.submit :add%>
<%end%>

<h4>Winemakers</h4>
<table>
  <tr>
    <th>Nombre</th>
    <th>Edad</th>
    <th>Nacionalidad</th>
  </tr>
<%@wine.winemakers.each do |winemaker|%>
  <tr>
    <td><%=winemaker.name%></td>
    <td><%=winemaker.age%></td>
    <td><%=winemaker.country%></td>
    <td>
      <%=winemaker.magazine.name%>
    </td>
  </tr>
<%end%>
</table>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<% if user_signed_in? %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cepas</th>
      <th>Score</th>
      <th>Agregar cepas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td>
          <ul>
          <%wine.cepas.order(name: :asc).each do |cepa|%>

              <li><%=cepa.name%></li>
          <%end%>
          </ul>
        </td>
        <td><%= wine.score %></td>
        <% if current_user.admin %>

        <td><%= form_with(url: wine_cepas_path(wine), local: true) do |f|%>
              <%= f.text_field :name%> 
              <%= f.submit :Add%>
            <%end%>
        </td>
          
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <h1>Iniciar sesion para ver el contenido</h1>
<% end %>

<br>

<% if user_signed_in?%>
  <% if current_user.admin %>
    <%= link_to 'New Wine', new_wine_path %>
  <% end %>
<% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.score %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>